<a href="https://colab.research.google.com/github/Akshitha-7773/30-days-PYTHON/blob/main/DAY_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**NUMPY**

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
zeros=np.zeros(5)
ones=np.ones(5)
print("zeros:",zeros)
print("ones:",ones)

zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1.]


In [6]:
import numpy as np
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)

[11 22 33]
[ 9 18 27]
[10 40 90]


In [7]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[1:4])
print(arr[-1])

10
[20 30 40]
50


In [10]:
import numpy as np
matrix=np.array([[1,2,3],
                [4,5,6]])
print(matrix)
print("shape",matrix.shape)
print("element",matrix[1][2])

[[1 2 3]
 [4 5 6]]
shape (2, 3)
element 6


In [12]:
import numpy as np
arr=np.array([1,4,9,16])
print("square root:",np.sqrt(arr))
print("sum:",np.sum(arr))
print("mean:",np.mean(arr))
print("max:",np.max(arr))


square root: [1. 2. 3. 4.]
sum: 30
mean: 7.5
max: 16


In [13]:
import numpy as np
marks=np.array([45,67,89,34,90])
passed=marks[marks>=50]
print("passed students marks:",passed)

passed students marks: [67 89 90]


In [15]:
import numpy as np
random_numbers=np.random.randint(1,100,size=10)
print(random_numbers)

[37 95 70 54 47 34 78 93 10  4]


In [19]:
import numpy as np
prices=np.array([100,200,300])
discount=10
final_price=prices-(prices*discount/100)
print(final_price)
total_bill=sum(final_price)
print(total_bill)

[ 90. 180. 270.]
540.0


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped =arr.reshape(2,3)
flattened=reshaped.flatten()
print("reshaped:",reshaped)
print("flattened:",flattened)

reshaped: [[1 2 3]
 [4 5 6]]
flattened: [1 2 3 4 5 6]
